name: transcriber_whisper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  audioplayers: ^6.2.0
  diffutil_dart: ^4.0.1
  desktop_drop: ^0.5.0
  dotted_border: ^2.1.0
  diff_match_patch: ^0.4.1
  equatable: ^2.0.7
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  flutter_audio_waveforms: ^1.2.1+8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  http: ^1.3.0
  http_parser: ^4.1.2
  path: ^1.9.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.2
  socket_io_client: ^3.0.2
  pretty_diff_text: ^2.0.0
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/audio/
